name: Build site

on:
  workflow_dispatch:
  schedule:
    # 12am UTC (4pm PST) every day
    # One hour after daily job https://app.circleci.com/settings/project/github/storybookjs/storybook/triggers
    - cron: '0 16 * * *'

jobs:
  compute:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: |
          curl -X POST -d '{}' ${{ secrets.BUILD_SITE_URL }}
